// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase: {
    apiKey: "**REMOVED**",
    authDomain: "top-6-653f6.firebaseapp.com",
    projectId: "top-6-653f6",
    storageBucket: "top-6-653f6.appspot.com",
    messagingSenderId: "153442619556",
    appId: "1:153442619556:web:9482f2d062e8ad8d899631",
    measurementId: "G-FM4R6MEGX5"
  }
};
