// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: false,
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase:  {
    apiKey: "**REMOVED**",
    authDomain: "top-6-653f6.firebaseapp.com",
    projectId: "top-6-653f6",
    storageBucket: "top-6-653f6.appspot.com",
    messagingSenderId: "153442619556",
    appId: "1:153442619556:web:9482f2d062e8ad8d899631",
    measurementId: "G-FM4R6MEGX5"
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
