// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase: {
    apiKey: '***REMOVED***',
    authDomain: 'beping-196714.firebaseapp.com',
    databaseURL: 'https://beping-196714.firebaseio.com',
    projectId: 'beping-196714',
    storageBucket: 'beping-196714.appspot.com',
    messagingSenderId: '169133988850'
  }
};
